### PR TITLE
Don't treat string as a pane

### PR DESCRIPTION
**Pull request by myshov**
In some cases `options.pane` consists string instead of pane of markers.

### CODE REVIEW

**Comment by bardt** [comment]
So what is the reason of `options.pane` being a string? Maybe we should find the roots of the problem?

**Comment by myshov** [comment]
@bardt I don't have so much time regarding this for now. Maybe we should create ticket in Jira?

**Comment by bardt** [comment]
I can't accept this request. Looks like we added an option `pane` which conflicts with built-in options. Try to rename it and check if it helps.

**Comment by ktoto** [comment]
It's seems like we must add default pane like `markerPane` and use `this.getPane()` instead `this._getPane()`

**Comment by ovvost** [comment]
@bardt @ktoto see again.

**Comment by bardt** [comment]
@ovvost looks right. Does demo page work with and without passing pane as an option?

**Comment by ovvost** [comment]
@bardt Yes.

**Comment by bardt** [comment]
I'd prefer @ilfa to see it and then merge.

**Comment by ilfa** [comment]
:+1:

**Comment by ktoto** [comment]
:+1:

**Pull request merged**
